version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - gocritic
    - misspell
    - staticcheck
    - unused

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      extra-rules: true
